AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Layout/IndentationStyle:
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Width: 1

Layout/TabIndentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
